//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankInvent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChemLabEntities : DbContext
    {
        public ChemLabEntities()
            : base("name=ChemLabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionLog> ActionLog { get; set; }
        public virtual DbSet<ActionLogPassport> ActionLogPassport { get; set; }
        public virtual DbSet<AuthActivity> AuthActivity { get; set; }
        public virtual DbSet<AuthHistory> AuthHistory { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Filial> Filial { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<PassportTnpa> PassportTnpa { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Protocol> Protocol { get; set; }
        public virtual DbSet<Protocol_15062021> Protocol_15062021 { get; set; }
        public virtual DbSet<Protocol_old> Protocol_old { get; set; }
        public virtual DbSet<ProtocolResult> ProtocolResult { get; set; }
        public virtual DbSet<ProtocolRoom> ProtocolRoom { get; set; }
        public virtual DbSet<ProtocolTest> ProtocolTest { get; set; }
        public virtual DbSet<ProtocolTool> ProtocolTool { get; set; }
        public virtual DbSet<ProtocolTool_old> ProtocolTool_old { get; set; }
        public virtual DbSet<Recipient> Recipient { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Room_old> Room_old { get; set; }
        public virtual DbSet<SampleLocation> SampleLocation { get; set; }
        public virtual DbSet<SampleSource> SampleSource { get; set; }
        public virtual DbSet<SampleType> SampleType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestDensTnpa> TestDensTnpa { get; set; }
        public virtual DbSet<TestObject> TestObject { get; set; }
        public virtual DbSet<TestTnpa> TestTnpa { get; set; }
        public virtual DbSet<TestType> TestType { get; set; }
        public virtual DbSet<Tool> Tool { get; set; }
        public virtual DbSet<ToolType> ToolType { get; set; }
        public virtual DbSet<ToolType_old> ToolType_old { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users2old> Users2old { get; set; }
        public virtual DbSet<Protocol_trash> Protocol_trash { get; set; }
        public virtual DbSet<Protocol_updated> Protocol_updated { get; set; }
        public virtual DbSet<ProtocolResult_trash> ProtocolResult_trash { get; set; }
        public virtual DbSet<ProtocolResult_updated> ProtocolResult_updated { get; set; }
        public virtual DbSet<Tool_old> Tool_old { get; set; }
        public virtual DbSet<LastTanksResultMoz> LastTanksResultMoz { get; set; }
        public virtual DbSet<LastTanksResultPol> LastTanksResultPol { get; set; }
        public virtual DbSet<LastMechanResultMoz> LastMechanResultMoz { get; set; }
    }
}
