//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankInvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tool()
        {
            this.ToolType = new HashSet<ToolType>();
        }
    
        public System.Guid id { get; set; }
        public int filialid { get; set; }
        public string name { get; set; }
        public string sernum { get; set; }
        public string regnum { get; set; }
        public Nullable<short> year { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public bool actual { get; set; }
        public string fullname { get; set; }
        public string comment { get; set; }
    
        public virtual Filial Filial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolType> ToolType { get; set; }
    }
}
