//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankInvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trl_tanktype
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<short> IsSteel { get; set; }
    }
}
